[package]
name = "si70xx"
version = "0.3.0"
edition = "2021"
rust-version = "1.60.0"

[dependencies]
cortex-m = "0.7.*"
cortex-m-rt = "0.7.*"
cortex-m-semihosting = "0.5.*"
stm32l4xx-hal = { version = "0.7.*", features = ["stm32l476"]}

[build-dependencies]
cc = "1.0.25"
